alias l='ls --time-style=long-iso -lF --color=auto'
alias la='ls --time-style=long-iso -la --color=auto'
alias lad='ls -d .*(/)'
alias lh='ls --time-style=long-iso -hAl --color=auto'
alias ll='ls --time-style=long-iso -l --color=auto'
alias ls='ls -CF --color=auto'
alias lsa='ls -a .*(.)'
alias lsbig='ls --time-style=long-iso -flh *(.OL[1,10])'
alias lsd='ls -d *(/)'
alias lse='ls -d *(/^F)'
alias lsl='ls --time-style=long-iso -l *(@)'
alias lsnew='ls --time-style=long-iso -rtlh *(D.om[1,10])'
alias lsnewdir='ls --time-style=long-iso -rthdl *(/om[1,10]) .*(D/om[1,10])'
alias lsold='ls --time-style=long-iso -rtlh *(D.Om[1,10])'
alias lsolddir='ls --time-style=long-iso -rthdl *(/Om[1,10]) .*(D/Om[1,10])'
alias lss='ls --time-style=long-iso -l *(s,S,t)'
alias lssmall='ls --time-style=long-iso -Srl *(.oL[1,10])'
alias lsw='ls --time-style=long-iso -ld *(R,W,X.^ND/)'
alias lsx='ls --time-style=long-iso -l *(*)'

